#!/bin/bash

set -e

SRC_FOLDER=${1?"Usage: $0 SRC_FOLDER"}

CURRENT_FOLDER="$(pwd)"
SRC_FOLDER=$(realpath "${SRC_FOLDER}")

cd "${SRC_FOLDER}"

export COUNT_OK=0
export COUNT_KO=0

while read -r filename; do
  echo "${filename}"
  ffmpeg -nostdin -y -loglevel error -i "${filename}" "${filename}.wav"
  EXIT_CODE=$?
  if [ ${EXIT_CODE} -eq 0 ]; then
    COUNT_OK=$((COUNT_OK + 1))
  else
    COUNT_KO=$((COUNT_KO + 1))
  fi
done <<<"$(find "." -name "*.aif")"

cd "${CURRENT_FOLDER}"

echo "Count ok: ${COUNT_OK}"
echo "Count ko: ${COUNT_KO}"
