#!/bin/bash

set -e

SRC_PLAYLIST=${1?"Usage: $0 SRC_PLAYLIST DST_FOLDER"}
DST_FOLDER=${2?"Usage: $0 SRC_PLAYLIST DST_FOLDER"}

mkdir -p "${DST_FOLDER}"
echo "${SRC_PLAYLIST}" >"${DST_FOLDER}/README.md"

while read -r filename; do
  echo "${filename} -> ${DST_FOLDER}"
  cp "${filename}" "${DST_FOLDER}"
done <<<"$(cat "${SRC_PLAYLIST}" | grep -e "^file" | cut -d '/' -f 3- | sed 's/%20/ /g' | sed 's/%23/#/g')"
