#!/bin/bash

set -e

SRC_FOLDER=${1?"Usage: $0 SRC_FOLDER DST_FOLDER"}
DST_FOLDER=${2?"Usage: $0 SRC_FOLDER DST_FOLDER"}

CURRENT_FOLDER="$(pwd)"
SRC_FOLDER=$(realpath "${SRC_FOLDER}")
DST_FOLDER=$(realpath "${DST_FOLDER}")

mkdir -p "${DST_FOLDER}"
cd "${SRC_FOLDER}"

export COUNT_OK=0
export COUNT_KO=0

while read -r filename; do
  directory="$(dirname "${filename}")"
  mkdir -p "${DST_FOLDER}/${directory}"
  dest="${filename%.*}"
  dest="${dest}.decoded.aif"
  dest="${DST_FOLDER}/${dest}"
  echo "${filename} -> ${dest}"
  "${CURRENT_FOLDER}"/abledecoder "${filename}" "${dest}"
  EXIT_CODE=$?
  if [ ${EXIT_CODE} -eq 0 ]; then
    COUNT_OK=$((COUNT_OK + 1))
  else
    COUNT_KO=$((COUNT_KO + 1))
  fi
done <<<"$(find "." -name "*.aif")"

cd "${CURRENT_FOLDER}"

echo "Count ok: ${COUNT_OK}"
echo "Count ko: ${COUNT_KO}"
